name: Deploy frontend

on:
  release:
    types: [published]

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci -w battleship3-frontend
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Run code builders
        run: |
          npm run generate:graphql-typings
          npm run generate:contract-typings
        working-directory: frontend
      - name: Build
        run: npm run build
        working-directory: frontend
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          branch: gh-pages
          folder: frontend/dist/frontend
